parameters:
  - name: PythonVersion
    type: string

jobs:
  - job: Check
    steps:
      - template: ../steps/provision.yaml
        parameters:
          PythonVersion: ${{ parameters.PythonVersion }}
      
      - template: ../steps/install.yaml
        
      - script: |
          black --check --diff --target-version=py38 $SOURCE_FILES          
        env:
          SOURCE_FILES: "src tests"
        displayName: "Run black"
      
      - script: |
          mypy $SOURCE_FILES
        env:
          SOURCE_FILES: "src tests"
        displayName: "Run mypy"
      
      - script: |
          isort --check --diff $SOURCE_FILES
        env:
          SOURCE_FILES: "src tests"
        displayName: "Run isort"

      - script: |
          flake8 $SOURCE_FILES
        env:
          SOURCE_FILES: "src tests"
        displayName: "Run flake8"
