parameters:
  - name: PythonVersion
    type: string
  - name: PypiToken
    type: string
  - name: Repository
    type: string
    default: 'pypi'


jobs:
  - job: publish
    steps:
      - template: ../steps/provision.yaml
        parameters:
          PythonVersion: "3.8"

      - template: ../steps/install.yaml
      
      - script: |
          poetry version ${VERSION}
        env:
          VERSION: $(Build.SourceBranch)
        
      - script: |
          poetry build
        displayName: "Poetry build"

      - script: |
          poetry publish -r ${REPOSITORY}
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ parameters.PypiToken }}
          REPOSITORY: ${{ parameters.Repository }}
        displayName: "Poetry publish"
        
