parameters:
  - name: PythonVersion
    type: string
  - name: PypiToken
    type: string
  - name: Repository
    type: string
    default: 'pypi'


jobs:
  - job: publish
    steps:
      - template: ../steps/provision.yaml
        parameters:
          PythonVersion: ${{ parameters.PythonVersion }}

      - template: ../steps/install.yaml
      
      - script: |
          poetry version ${VERSION}
        env:
          VERSION: $(Build.SourceBranchName)
          POETRY_CACHE_DIR: $(Pipeline.Workspace)/.cache/pypoetry/
        
      - script: |
          poetry build
        displayName: "Poetry build"
        env:
          POETRY_CACHE_DIR: $(Pipeline.Workspace)/.cache/pypoetry/

      - script: |
          poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ parameters.PypiToken }}
          #REPOSITORY: ${{ parameters.Repository }}
          POETRY_CACHE_DIR: $(Pipeline.Workspace)/.cache/pypoetry/
        displayName: "Poetry publish"
        
