parameters:
  - name: PythonVersion
    type: string
    default: "3.8"

jobs:
  - job: Check
    steps:
      - template: ../steps/provision.yaml
        parameters:
          PythonVersion: ${{ parameters.PythonVersion }}
      
      - template: ../steps/install.yaml
        
      - script: |
          black --check --diff --target-version=py38 $SOURCE_FILES
          flake8 $SOURCE_FILES
          mypy $SOURCE_FILES
          isort --check --diff $SOURCE_FILES
        env:
          SOURCE_FILES: "src tests"
        displayName: "Run checks"