parameters:
  - name: PythonVersion
    type: string
  - name: PypiToken
    type: string


stages:
  - stage: publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - template: ../jobs/publish.yaml
        parameters:
          PypiToken: ${{ parameters.PypiToken }}
          PythonVersion: ${{ parameters.PythonVersion }}
