parameters:
  - name: PypiToken
    type: string


stages:
  - stage: publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - template: ../jobs/sdk-publish.yaml
        parameters:
          PypiToken: ${{ parameters.PypiToken }}
