parameters:
  - name: PythonVersion
    type: string
    default: "3.8"
  - name: jobs
    type: object


stages:
  - stage: test
    jobs:
      - template: ../jobs/check.yaml@templates
        parameters:
          PythonVersion: ${{ parameters.PythonVersion }}
      
      - template: ../jobs/test.yaml@templates
        parameters:
          jobs: ${{ parameters.jobs }}
